### ISSUE TITLE
CollectionView에서 XIB로 DiffableDataSource를 구현하는 것에 대한 이슈

### ISSUE THREAD

**Issue by panther222128** [panther222128/sidedish#3]
XIB를 활용해 XIB에 View 요소를 추가하고 View 요소에 필요한 값을 주입할 때 'unexpectedtly found nil' 에러가 발생함

찾아본 결과 XIB의 Layout을 결정하지 못해 컴파일 시 XIB가 존재하는지 아닌지 여부에 대해 존재하지 않는다는 판단으로 XIB의 View 요소는 존재하지 않음

달리 표현하면 Collection View에서 Cell의 개수는 정확하게 표현하고 있지만 Cell 내의 View 요소를 표현하지 못함

즉 Cell 내의 View 요소의 Layout이 결정되지 않아 컴파일에서 nil 상태로 반환하는 것으로 보임

프로젝트의 빠른 진행을 위하려면 Programmatically 혹은 only Storyboard 활용이 필요하다고 보임

그 이유는 DiffableDataSource에서 XIB를 활용하는 것이 까다롭고 예시마저 검색 시 드물게 보임

참고 링크
<https://zeddios.tistory.com/1197>
<https://stackoverflow.com/questions/55640408/xibs-iboutlets-returning-nil-when-using-xib-in-storyboard>
<https://stackoverflow.com/questions/52066101/cannot-create-a-custom-view-using-xib-file-due-to-nil-subviews>

느낀점: 아래 링크처럼 XIB를 간략하게 사용해볼 수 있겠지만 Layout 설정 등 까다로운 작업이 요구되므로 깊이있는 이해가 필요함

<https://velog.io/@panther222128/UICollectionView-with-XIB-Practice>

해결: 스토리보드 내 CollectionView에서 Cell의 사이즈를 Custom으로 설정

**Comment by Lia316** [comment]
### 👉🏻 결정
xib 로 충분히 구현할 수 있다는 것을 파악한 후에, xib로 구현함
### 🐞 bug
화면에 cell은 뜨는데 label이 안 뜨는 문제 발견
### ⚒️ fix
- diffableDataSource 에서 cell 을 편집함
-  collection view의 estimated size는 none으로, cell의 크기는 custom 으로 설정하여 label 이 들어갈 공간을 확보함
